<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEonhSWz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEonhSWz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEonhSWz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEonhSWz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEonhSWz\App_KernelDevDebugContainer([
    'container.build_hash' => 'EonhSWz',
    'container.build_id' => '2d491470',
    'container.build_time' => 1770122859,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEonhSWz');
