<?php

namespace ContainerEonhSWz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()'] = ($container->privates['.service_locator.1vYpZ1B'] ?? $container->load('get_ServiceLocator_1vYpZ1BService'))->withContext('kernel::registerContainerConfiguration()', $container);
    }
}
